server:
  port: 8080

# ============================= #
# ====== Local Database ======= #
# ============================= #
# TODO: URL, username, ddl-auto 확인하기
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql:3306/sclive?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  redis:
    host: db-redis
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: BackendApplication
  auth:
    secretKey: 6v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-

mybatis:
  type-aliases-package: com.codragon.sclive.dao
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.codragon.sclive: debug
